---

zadara_cloud_console:
    url: 'https://manage.zadarastorage.com'

zadara_vpsa:
    volume_export_path: '192.168.240.145:/export/pazuzu'

logging:
    version: 1
    disable_existing_loggers: False

    formatters:
        simple:
            format: '%(asctime)-15s - %(name)s:%(lineno)s - %(levelname)s - %(message)s'
    handlers:
        console:
            class: logging.StreamHandler
            level: DEBUG
            formatter: simple
            stream: ext://sys.stdout
        file_handler:
            class: logging.handlers.RotatingFileHandler
            level: DEBUG
            formatter: simple
            filename: zadara.log
            maxBytes: 10485760    # 10M
            backupCount: 3
    root:
        level: INFO
        handlers: [ console, file_handler ]
